apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: yourusername/my-go-app:v1  # <- Change this to your Docker image
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: config-volume
          mountPath: /root/local.yaml
          subPath: local.yaml
      volumes:
      - name: config-volume
        configMap:
          name: go-app-config
