server:
  port: 8086

logging:
  level: debug

app:
  name: go-microservice
  env: dev

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: mydb
  sslmode: disable


cache:    
  enabled: true
  host: localhost
  port: 6379
  password: password
  db: 0
