apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
    - port: 8086
      targetPort: 8086
  type: NodePort  # Use LoadBalancer if you're on a cloud provider
